# Generated by Django 5.1.2 on 2024-11-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("uId", models.CharField(max_length=18, unique=True)),
                ("sex", models.CharField(max_length=10)),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("A", "健康"),
                            ("B", "亚健康"),
                            ("C", "不健康"),
                            ("D", "已逝"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
