# Generated by Django 5.1.2 on 2024-11-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cushealth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerhealth",
            name="content",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
